//!! generated by clutz.
// Generated from src/closure/hello.js
declare namespace ಠ_ಠ.clutz.app.hello {
  function sayHello (name : string ) : void ;
}
declare module 'goog:app.hello' {
  import hello = ಠ_ಠ.clutz.app.hello;
  export = hello;
}
